<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Validation\ValidationException;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array<int, class-string<Throwable>>
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     */
    public function render($request, Throwable $e)
    {
        if ($request->ajax() || $request->segment(1) === 'api') {
            switch (true) {
                case $e instanceof ValidationException:
                    return response()->json([
                        'error' => [
                            'message' => trans('validation.validation_error'),
                            'errors'  => $e->errors()
                        ]
                    ], $e->status);

            }
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
